export default {
  AUTH_LOGIN: 'EXPRESS_AUTH_LOGIN',
  AUTH_LOGOUT: 'EXPRESS_AUTH_LOGOUT',
  AUTH_ERROR: 'EXPRESS_AUTH_ERROR',
  AUTH_SET_TOKEN: 'EXPRESS_AUTH_SET_TOKEN',
  AUTH_VERIFY: 'EXPRESS_AUTH_VERIFY'
};
